#!/bin/bash
# yl2 - küsib kuu numbrit (1-12) ja väljastab aastaaja
echo "Sisesta kuu number (1-12): "
read kuu
case $kuu in
    ''|*[!0-9]*) echo "vigane sisend"; exit 1 ;;
esac
if test $kuu -eq 12 -o $kuu -eq 1 -o $kuu -eq 2
then
    echo "Praegu on talv"
elif test $kuu -ge 3 -a $kuu -le 5
then
    echo "Praegu on kevad"
elif test $kuu -ge 6 -a $kuu -le 8
then
    echo "Praegu on suvi"
elif test $kuu -ge 9 -a $kuu -le 11
then
    echo "Praegu on sügis"
else
    echo "vigane sisend"
fi
