#!/bin/bash
# yl1 - väljastab sisseehitatud tsüklitega 5 rida, igas reas 5 tärni
for (( i = 1; i <= 5; i++ ))
do
    for (( j = 1; j <= 5; j++ ))
    do
        echo -n "* "
    done
    echo ""
done
