#!/bin/bash
# yl2 - väljastab kasutaja sisestatud ridade ja tärnide arvuga ristküliku
read -p "Sisesta ridade arv: " read_arv
read -p "Sisesta tärnide arv reas: " tarnid
if ! [[ $read_arv =~ ^[1-9][0-9]*$ && $tarnid =~ ^[1-9][0-9]*$ ]]
then
    echo "Vigane sisend - sisesta positiivsed täisarvud"
    exit 1
fi
for (( i = 1; i <= read_arv; i++ ))
do
    for (( j = 1; j <= tarnid; j++ ))
    do
        echo -n "* "
    done
    echo ""
done
