#!/bin/bash
# Skript arvutab vajalike busside arvu; kui osa reisijaid ei mahu täisbussidesse, lisatakse üks buss
echo -n "Sisesta reisijate arv: "
read reisijad
echo -n "Sisesta kohtade arv bussis: "
read kohad
bussid=$(( reisijad / kohad ))
if [ $(( reisijad % kohad )) -gt 0 ]
then
    bussid=$(( bussid + 1 ))
fi
echo "Kokku on vaja $bussid bussi"
