#!/bin/bash
# Skript kontrollib käivitamisel parameetrina antud täisarvu paarsust
if [ $# -ne 1 ] || ! [[ $1 =~ ^-?[0-9]+$ ]]
then
    echo "Kaivita see skript koos arvuga mille paarsus soovid kontrollida. Näiteks: ./paarsus 3"
    exit 1
fi
if [ $(( $1 % 2 )) -eq 0 ]
then
    echo "Antud arv on paaris"
else
    echo "Antud arv on paaritu"
fi
